### ISSUE TITLE
Handle different cluster sizes when adding related studies

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nfportalutils#65]
Related to https://github.com/nf-osi/jobs/commit/cf03265e9d29697a2f580bf7a293bf2220270f2c. When new studies are added, the limit of cluster size (10) can be exceeded, which leads to an error when trying to upload the results. This leads to manual handling of hard-coding a larger number of clusters to reduce cluster size and avoid the error (either this or increasing the cluster size allowed by the schema). Maybe this should be more dynamically handled by the script through proposing a new cluster parameter if we see that it leads to a cluster size > 10 and rerunning as needed.

**Comment by anngvu** [comment]
Actually, easier solution is just to take the number of related studies allowed by the list column. For example, if cluster includes 13 members but schema only allows 10, take first (or best?) 10.

**Comment by allaway** [comment]
Hmm, with this solution, won't some studies be missing from the list of related studies?

Unfortunately, the way the clusters are currently being generated, there is no ranking within the cluster. That is to say, we're taking a cluster of e.g. 13 and saying these 13 are all related to one another, because we are simply cutting all trees at the same height to get the desired number of clusters. 

We could (maybe should) refactor this code to evaluate each study and select the, say, 5-10 nearest neighbors by euclidean distance). This would give us more control over the number of studies presented, and probably would improve the results b/c we could select the nearest results, and we could also assign the list-column in order of distance, so the first study to show up is the closest, second is second closest, and so on.

**Comment by anngvu** [comment]
This will soon be resolved using KNN as an alternative, since increasing cluster number was a temp fix, and recent runs had list that exceeded size 10 again.
