### ISSUE TITLE
Function to email folks who are missing annotations 

### ISSUE THREAD

**Issue by allaway** [nf-osi/nfportalutils#7]
@jaybee84 @kthrog - can you help me scope this function? What would you want this to do? (This is a follow up on the conversation we had with JOB in our last biweekly).

**Comment by kthrog** [comment]
So, this is just a rough idea, but here's a sketch of what I'm thinking, and how it might be executed. 

**What I'd like:**
- to receive an email when a project has gone a certain amount of time (e.g., 6 months, or maybe 1 year is more realistic) since creation, with no new files added
- to receive an email when a project's files have gone a certain amount of time (e.g., 1 month) with no annotations (or at least blank values for keys we deem essential)
- in a perfect world, I'd like those emails to then allow me to trigger an templated email to the investigator saying either a) we've noticed you haven't uploaded any files, please see docs here, contact us if needed or b) we've noticed you haven't added annotations to the files you've uploaded, please use the data curator app to annotate, contact us if needed

**How it might be done:**
- using a couple of keys we deem essential/should never be blank in annotations considered complete (e.g., resourceType, dataType, assay), look for blank values in those keys in the Portal - Files table and compare with file creation date -- if more than the allotted period of 'annotation time' (e.g., 1 month) has passed, send an email
- if we wanted to get really fancy, perhaps we could do the above, and then merge with data from the IncomingData portal table, add a column to start adding the end of award date (we don't currently collect this, but could, for all DSPs that completed it), and if the end of award date < 3 months away, notify everyone (us, funder, investigator) and send a templated email with instructions

Will keep thinking about this!

**Comment by anngvu** [comment]
Closing as scoped and implemented in https://github.com/nf-osi/jobs/issues/23
